//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class After
    {
        public int AfterID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string AfterYy { get; set; }
        public string AfterJg { get; set; }
        public string KName { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
    }
}
